# Generated by Django 3.2 on 2021-04-25 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('PRIMARY', 'Primary'), ('MIDDLE', 'Middle'), ('HIGH', 'High')], default='PRIMARY', max_length=50)),
                ('established_on', models.DateField(verbose_name='established_on')),
                ('address', models.TextField(verbose_name='address')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='updated_on')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created_on')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.city', verbose_name='city')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.country', verbose_name='country')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
    ]
