# Generated by Django 3.2 on 2021-04-25 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20210425_2021'),
        ('school', '0002_alter_school_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.state', verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.city', verbose_name='city'),
        ),
    ]
