# Generated by Django 3.2 on 2021-04-25 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20210425_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=50, verbose_name='city_code'),
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.CharField(max_length=50, verbose_name='state_code'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50, verbose_name='state_name'),
        ),
    ]
